#!/usr/bin/env bash
#
# Generate .env for the machine this is being deployed on: detects the hostname,
# timezone, Apache log directory and its file-naming convention, and generates a
# Grafana admin password.
#
# Safe to re-run: an existing .env is never overwritten unless --force is given,
# and an existing GF_ADMIN_PASSWORD is always carried over so the password you
# already have keeps working.
#
# Usage:  ./scripts/setup.sh [--force]

set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
ENV_FILE="$ROOT/.env"
FORCE=0
[[ "${1:-}" == "--force" ]] && FORCE=1

if [[ -f "$ENV_FILE" && $FORCE -eq 0 ]]; then
  echo "$ENV_FILE already exists. Re-run with --force to regenerate it"
  echo "(your existing GF_ADMIN_PASSWORD would be preserved)."
  exit 0
fi

say() { printf '  %-22s %s\n' "$1" "$2"; }

echo "Detecting environment"

# --- hostname -------------------------------------------------------------
APACHE_HOST="$(hostname -f 2>/dev/null || hostname 2>/dev/null || echo apache)"
say "host label" "$APACHE_HOST"

# --- timezone -------------------------------------------------------------
APACHE_TZ=""
if command -v timedatectl >/dev/null 2>&1; then
  APACHE_TZ="$(timedatectl show -p Timezone --value 2>/dev/null || true)"
fi
if [[ -z "$APACHE_TZ" && -r /etc/timezone ]]; then
  APACHE_TZ="$(tr -d '[:space:]' < /etc/timezone)"
fi
if [[ -z "$APACHE_TZ" && -L /etc/localtime ]]; then
  # /etc/localtime -> /usr/share/zoneinfo/Europe/Berlin
  APACHE_TZ="$(readlink -f /etc/localtime | sed 's#.*/zoneinfo/##')"
fi
APACHE_TZ="${APACHE_TZ:-UTC}"
say "timezone" "$APACHE_TZ"

# --- Apache log directory and naming convention ---------------------------
# Debian/Ubuntu use access.log; RHEL/CentOS/Fedora use access_log.
APACHE_LOG_DIR=""
APACHE_ACCESS_LOG=""
APACHE_ERROR_LOG=""

for d in /var/log/apache2 /var/log/httpd /var/log/apache; do
  [[ -d "$d" ]] || continue
  for pair in "access.log:error.log" "access_log:error_log"; do
    a="${pair%%:*}"; e="${pair##*:}"
    # Match if the live file exists, or any rotated variant does -- a brand new
    # server may have an empty log dir but the convention is still detectable.
    if [[ -e "$d/$a" ]] || compgen -G "$d/${a}*" >/dev/null 2>&1; then
      APACHE_LOG_DIR="$d"; APACHE_ACCESS_LOG="$a"; APACHE_ERROR_LOG="$e"
      break 2
    fi
  done
  # Directory exists but is empty: fall back to the distro default naming.
  if [[ -z "$APACHE_LOG_DIR" ]]; then
    APACHE_LOG_DIR="$d"
    if [[ "$d" == "/var/log/httpd" ]]; then
      APACHE_ACCESS_LOG="access_log"; APACHE_ERROR_LOG="error_log"
    else
      APACHE_ACCESS_LOG="access.log"; APACHE_ERROR_LOG="error.log"
    fi
    break
  fi
done

if [[ -z "$APACHE_LOG_DIR" ]]; then
  APACHE_LOG_DIR="/var/log/apache2"
  APACHE_ACCESS_LOG="access.log"
  APACHE_ERROR_LOG="error.log"
  echo
  echo "  WARNING: no Apache log directory found. Defaulting to $APACHE_LOG_DIR."
  echo "           Edit APACHE_LOG_DIR in .env before starting the stack."
fi

say "log directory" "$APACHE_LOG_DIR"
say "log file names" "$APACHE_ACCESS_LOG / $APACHE_ERROR_LOG"

# --- readability ----------------------------------------------------------
# Alloy runs as root inside its container and can always read these. This check
# is about scripts/import_logs.py, which runs on the host as the invoking user.
if [[ -e "$APACHE_LOG_DIR/$APACHE_ACCESS_LOG" ]] && ! [[ -r "$APACHE_LOG_DIR/$APACHE_ACCESS_LOG" ]]; then
  echo
  echo "  NOTE: $APACHE_LOG_DIR/$APACHE_ACCESS_LOG is not readable by $(id -un)."
  echo "        The stack itself is fine (Alloy reads as root in its container),"
  echo "        but scripts/import_logs.py needs read access. Either add yourself"
  echo "        to the log group (Debian: sudo usermod -aG adm $(id -un); re-login)"
  echo "        or run the import with  sudo -E ."
fi

# --- password -------------------------------------------------------------
GF_ADMIN_PASSWORD=""
if [[ -f "$ENV_FILE" ]]; then
  GF_ADMIN_PASSWORD="$(grep -E '^GF_ADMIN_PASSWORD=' "$ENV_FILE" | head -1 | cut -d= -f2- || true)"
fi
if [[ -n "$GF_ADMIN_PASSWORD" ]]; then
  say "admin password" "carried over from existing .env"
else
  if command -v openssl >/dev/null 2>&1; then
    GF_ADMIN_PASSWORD="$(openssl rand -base64 24 | tr -d '/+=' | cut -c1-20)"
  else
    GF_ADMIN_PASSWORD="$(tr -dc 'A-Za-z0-9' < /dev/urandom | head -c 20)"
  fi
  say "admin password" "generated"
fi

# --- write ----------------------------------------------------------------
# Ports are written as literals: Docker Compose interpolates ${VAR} inside the
# compose file, not inside .env, so .env must not reference its own variables.
GRAFANA_PORT=3000
LOKI_PORT=3100
ALLOY_PORT=12345

umask 077
cat > "$ENV_FILE" <<EOF
# Generated by scripts/setup.sh -- see .env.example for what each value means.

APACHE_LOG_DIR=$APACHE_LOG_DIR
APACHE_ACCESS_LOG=$APACHE_ACCESS_LOG
APACHE_ERROR_LOG=$APACHE_ERROR_LOG

APACHE_HOST=$APACHE_HOST
APACHE_TZ=$APACHE_TZ

GF_ADMIN_PASSWORD=$GF_ADMIN_PASSWORD
GF_SERVER_ROOT_URL=http://localhost:$GRAFANA_PORT/

# 127.0.0.1 keeps everything private to this server; reach Grafana over an SSH
# tunnel. Only set 0.0.0.0 behind a firewall or TLS-terminating reverse proxy.
BIND_ADDR=127.0.0.1
GRAFANA_PORT=$GRAFANA_PORT
LOKI_PORT=$LOKI_PORT
ALLOY_PORT=$ALLOY_PORT

LOKI_MEM=512m
GRAFANA_MEM=384m
ALLOY_MEM=256m

LOKI_VERSION=3.5
ALLOY_VERSION=v1.12.0
GRAFANA_VERSION=12.1
EOF
chmod 600 "$ENV_FILE"

echo
echo "Wrote $ENV_FILE (mode 600)"

# --- python virtualenv for scripts/import_logs.py -------------------------
# The importer uses only the standard library, so nothing is installed here.
# The venv exists to pin which interpreter runs it, independently of whatever
# the system python3 happens to be.
VENV="$ROOT/.venv"
if [[ -x "$VENV/bin/python" ]]; then
  echo "Virtualenv already present at $VENV ($("$VENV/bin/python" --version 2>&1))"
elif command -v python3 >/dev/null 2>&1; then
  if python3 -m venv "$VENV" 2>/dev/null; then
    echo "Created virtualenv $VENV ($("$VENV/bin/python" --version 2>&1))"
    if [[ -f "$ROOT/requirements.txt" ]]; then
      "$VENV/bin/pip" install --quiet --upgrade pip >/dev/null 2>&1 || true
      "$VENV/bin/pip" install --quiet -r "$ROOT/requirements.txt" >/dev/null 2>&1 || true
    fi
  else
    echo "NOTE: could not create a virtualenv (python3-venv may not be installed)."
    echo "      scripts/import_logs.py still runs under the system python3 --"
    echo "      it needs no third-party packages."
  fi
else
  echo "NOTE: python3 not found. scripts/import_logs.py needs Python 3.9+."
fi

echo
echo "Next:"
echo "  docker compose up -d"
echo "  ./scripts/import_logs.py --discover --list   # optional: rotated history"
echo
echo "Grafana: http://127.0.0.1:$GRAFANA_PORT  user admin  password $GF_ADMIN_PASSWORD"
